apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: default
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: vortexgrid
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
spec:
  type: ClusterIP
  selector:
    app: prometheus
  ports:
    - name: http
      port: 9090
      targetPort: 9090
      protocol: TCP
    - name: pushgateway
      port: 9091
      targetPort: 9091
      protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vortexgrid-service-monitor
  namespace: default
  labels:
    release: prometheus
    app.kubernetes.io/part-of: vortexgrid
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: vortexgrid
  endpoints:
    - port: metrics
      interval: 10s
      path: /metrics